import "./globals.css";
import App from "@/components/layouts/app";
import {AppProvider} from "@/providers/AppProvider";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return [{lang: 'en-US'}, {lang: 'de'}]
}
async function getLessons() {
    const res = await fetch('https://lineup.dahk.am/api/lessons');
    const data = await res.json();
    return data;
}

export default async function RootLayout({children, params}) {
    const lessons = await getLessons();
    return (
        <html lang={(await params).lang}>
        <body>
        <AppProvider>
            <App lang={(await params)?.lang} params={params} lessons={lessons}>
                {children}
            </App>
        </AppProvider>
        </body>
        </html>
    );
}
